# Generated by Django 3.0.7 on 2020-07-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=40)),
                ('thumbnail', models.URLField()),
                ('processor', models.CharField(max_length=40)),
                ('RAM', models.CharField(max_length=40)),
                ('HD_capacity', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=40)),
                ('thumbnail', models.URLField()),
                ('processor', models.CharField(max_length=40)),
                ('RAM', models.CharField(max_length=40)),
                ('screen_size', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=40)),
            ],
        ),
    ]
